# Generated by Django 4.1.1 on 2022-09-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(),
        ),
    ]
