# Generated by Django 4.1.1 on 2022-09-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0003_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
