# Generated by Django 4.1.1 on 2022-10-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
